#!/bin/bash

IMAGE=$(mktemp).png

convert -size 3840x1080 xc:#181818 $IMAGE
PARAM='--textcolor=ffffff00 --insidecolor=ffffffff --ringcolor=ffffff3e \
--linecolor=ffffff00 --keyhlcolor=00000080 --ringvercolor=00000000 \
--insidevercolor=0000001c --ringwrongcolor=00000055 --insidewrongcolor=0000001c'

i3lock $PARAM -i $IMAGE > /dev/null 2>&1
rm $IMAGE
